### ISSUE TITLE
Where is the code and also why did you not PR this in.

### ISSUE THREAD

**Issue by Cuteistfox** [Colmines92/Goldberg-Emulator#1]

**Comment by Colmines92** [comment]
Easy. In my country 1gb of data is too expensive.
Precompiled binaries are much smaller than source code and I can manually upload it when needed, not every time I recompile them.

**Comment by Cuteistfox** [comment]
I think git only pushes the commits not yet on that places copy of the repo so unless you have 1gb of commits, it will be fine (when you create a MR on gitlab it creates a repo which is a clone of upstream where you can make commits and send them upstream). Also how did you get a copy of mr. goldberg to base this off?

**Comment by Cuteistfox** [comment]
(i closed it beacuase i dont think you will do it)
